name: Flutter Manually Build

on:
  schedule:
    # schedule build every night
    # - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-manual-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "manual"
